import type { VersionedDigest } from "../capabilities/index.js";

/** Product modes supported by one anonymous meeting. */
export type MeetingMode = "video_conference" | "audio_call" | "live";

/** Public creation command after boundary validation and normalization. */
export interface CreateMeetingCommand {
  /** Client-generated idempotency identifier. */
  readonly commandId: string;
  /** Meeting product mode. */
  readonly mode: MeetingMode;
  /** Untrusted display label normalized for storage. */
  readonly displayName: string;
  /** Independent 256-bit host capability generated by the browser. */
  readonly hostCapability: string;
  /** Independent 256-bit invite capability generated by the browser. */
  readonly inviteCapability: string;
  /** Random browser-generated device binding, not a fingerprint. */
  readonly deviceBinding: string;
  /** Request correlation identifier for the security audit. */
  readonly traceId: string;
}

/** Public join command after boundary validation and normalization. */
export interface JoinMeetingCommand {
  /** Public, non-secret meeting identifier. */
  readonly meetingId: string;
  /** Client-generated idempotency identifier. */
  readonly commandId: string;
  /** Invite capability extracted from the URL fragment by the frontend. */
  readonly inviteCapability: string;
  /** Untrusted display label normalized for storage. */
  readonly displayName: string;
  /** Random browser-generated device binding, not a fingerprint. */
  readonly deviceBinding: string;
  /** Request correlation identifier for the security audit. */
  readonly traceId: string;
}

/** Session material returned to the HTTP boundary after a committed command. */
export interface AnonymousMeetingSession {
  /** Public meeting identifier. */
  readonly meetingId: string;
  /** Public participant identifier. */
  readonly participantId: string;
  /** Opaque 256-bit token written only to an HttpOnly cookie. */
  readonly sessionToken: string;
  /** CSRF token returned in the body and kept in frontend memory. */
  readonly csrfToken: string;
  /** Product role assigned by server policy. */
  readonly role: "host" | "participant" | "viewer";
  /** True when an existing idempotent command was replayed. */
  readonly replayed: boolean;
}

/** Persistence command for creating a meeting and its first anonymous session. */
export interface PersistCreateMeeting {
  readonly commandId: string;
  readonly requestFingerprint: Buffer;
  readonly mode: MeetingMode;
  readonly displayName: string;
  readonly hostCapability: VersionedDigest;
  readonly inviteCapability: VersionedDigest;
  readonly session: PersistSessionMaterial;
  readonly traceId: string;
}

/** Persistence command for joining through one rotation-aware invite capability. */
export interface PersistJoinMeeting {
  readonly meetingId: string;
  readonly commandId: string;
  readonly requestFingerprint: Buffer;
  readonly displayName: string;
  readonly inviteCandidates: readonly VersionedDigest[];
  readonly session: PersistSessionMaterial;
  readonly traceId: string;
}

/** Digests and raw response tokens required to persist an anonymous session. */
export interface PersistSessionMaterial {
  readonly token: string;
  readonly tokenDigest: VersionedDigest;
  readonly csrfToken: string;
  readonly csrfDigest: VersionedDigest;
  readonly deviceBindingDigest: VersionedDigest;
}

/** Repository boundary for transactional anonymous meeting commands. */
export interface MeetingRepository {
  /** Creates exactly one meeting for an idempotency key and request fingerprint. */
  create(command: PersistCreateMeeting): Promise<AnonymousMeetingSession>;
  /** Joins exactly once while allowing safe replay to issue a replacement session. */
  join(command: PersistJoinMeeting): Promise<AnonymousMeetingSession>;
}
